""" vimwiki settings
set nocompatible
filetype plugin on
syntax on
let g:vimwiki_list = [{'path': '*',
                      \ 'syntax': 'markdown', 'ext': '.md', 'auto_tags': 1}]
let g:vimwiki_ext2syntax = {'.md': 'markdown'}

""" Set line length
set colorcolumn=80

" List invisible chracters (Dom)
set list                  " Show invisible characters
set listchars=tab:›\ ,eol:¬,trail:⋅ "Set the characters for the invisibles

" Highlight trailing whitespace (Paul)
:highlight TrailWhitespace ctermbg=red guibg=red
:match TrailWhitespace /\s\+$\| \+\ze\t/

""" Line numbers
" Pressing Control-N twice to toggle line numbers
" http://vim.wikia.com/wiki/Display_line_numbers
:nmap <C-N><C-N> :set number! relativenumber!<CR>

""" Toggle spell checking with ctrl-s ctrl-s
set spelllang=en_gb
nmap <silent> <leader>s :set spell!<CR>
" Automatically enable spell check on .md files
" https://robots.thoughtbot.com/vim-spell-checking
autocmd BufRead,BufNewFile *.md setlocal spell

""" NERDTree
map <C-n> :NERDTreeToggle<CR>

""" Paste settings
set pastetoggle=<F12>

""" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
